/**

 * Family Wealth AI OS V7

 * Transaction Service

 *

 * Responsibility:

 *

 * - Provide the standard business-facing entry point

 *   for creating Actual Transactions.

 *

 * - Convert business event data into the standard

 *   Transaction structure.

 *

 * - Keep business modules decoupled from the

 *   Transaction Manager implementation.

 *

 * - Publish system Transaction events.

 *

 * TransactionService does NOT perform:

 *

 * - Tax calculations

 * - Investment calculations

 * - Cost basis calculations

 * - Capital gain calculations

 * - Loan calculations

 * - Interest calculations

 * - Account balance calculations

 * - Cash Flow calculations

 * - Forecast calculations

 * - Simulation calculations

 *

 *

 * Architecture:

 *

 * Business Module

 *      ↓

 * TransactionService

 *      ↓

 * TransactionManager

 *      ↓

 * Transaction

 *      ↓

 * Financial Lines

 *      ↓

 * Account

 *

 *

 * IMPORTANT:

 *

 * TransactionService records Actual events.

 *

 * Planning / Forecast / Simulation data must not

 * automatically become Actual Transactions.

 */

const Transaction =

    require("./transaction");

/*

 * Event system.

 *

 * TransactionService publishes the standard

 * TRANSACTION_CREATED event after a transaction

 * has successfully entered the TransactionManager.

 */

let EventBus = null;

let EventTypes = null;

try {

    EventBus =

        require("../core/events/eventBus.js")

            .default ||

        require("../core/events/eventBus.js");

    EventTypes =

        require("../core/events/eventTypes.js")

            .default ||

        require("../core/events/eventTypes.js");

} catch (error) {

    /*

     * Event system is optional at this layer.

     *

     * Transaction recording itself must continue

     * to work even if the event system is not yet

     * available during staged development.

     */

    EventBus = null;

    EventTypes = null;

}

/**

 * TransactionService

 */

class TransactionService {

    constructor(transactionManager) {

        if (!transactionManager) {

            throw new Error(

                "TransactionManager is required."

            );

        }

        this.transactionManager =

            transactionManager;

    }

    // =====================================================

    // Core Transaction

    // =====================================================

    /**

     * Record a generic Actual Transaction.

     *

     * Business modules may provide already

     * calculated businessDetails.

     *

     * TransactionService does NOT calculate

     * business values.

     */

    recordTransaction(data = {}) {

        const transaction =

            data instanceof Transaction

                ? data

                : new Transaction(data);

        /*

         * Transactions generated by a business

         * module should identify their source.

         *

         * If the caller explicitly supplies a

         * source, preserve it.

         */

        if (

            !transaction.source ||

            transaction.source === "Manual"

        ) {

            transaction.source =

                data.source ||

                "BusinessModule";

        }

        transaction.normalize();

        const validation =

            transaction.validate();

        if (!validation.valid) {

            throw new Error(

                validation.errors.join(" ")

            );

        }

        const result =

            this.transactionManager

                .createTransaction(

                    transaction

                );

        /*

         * Publish system event only after the

         * TransactionManager successfully creates

         * the Actual Transaction.

         */

        this.publishTransactionCreated(

            result

        );

        return result;

    }

    /**

     * Publish Transaction Created event.

     *

     * Kept in a separate method so the core

     * transaction recording process remains clean.

     */

    publishTransactionCreated(

        transaction

    ) {

        if (

            !EventBus ||

            !EventTypes ||

            !EventTypes.TRANSACTION_CREATED

        ) {

            return null;

        }

        return EventBus.publish(

            EventTypes.TRANSACTION_CREATED,

            transaction

        );

    }

    // =====================================================

    // Income

    // =====================================================

    /**

     * Record an Income Actual event.

     *

     * Income calculations remain inside the

     * Income business module.

     *

     * This method only records the calculated result.

     */

    recordIncome(data = {}) {

        const {

            date,

            accountId,

            amount,

            currency = "USD",

            description = "",

            income = {},

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "INCOME",

            currency,

            description,

            source,

            lines: [

                {

                    accountId,

                    type: "INCOME",

                    amount,

                    direction: "IN",

                    cashEffect: true,

                    category:

                        income.category ||

                        "Income",

                    description

                }

            ],

            businessDetails: {

                income: {

                    ...income,

                    amount

                }

            }

        });

    }

    // =====================================================

    // Expense

    // =====================================================

    /**

     * Record an Expense Actual event.

     */

    recordExpense(data = {}) {

        const {

            date,

            accountId,

            amount,

            currency = "USD",

            description = "",

            expense = {},

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "EXPENSE",

            currency,

            description,

            source,

            lines: [

                {

                    accountId,

                    type: "EXPENSE",

                    amount,

                    direction: "OUT",

                    cashEffect: true,

                    category:

                        expense.category ||

                        "Expense",

                    description

                }

            ],

            businessDetails: {

                expense: {

                    ...expense,

                    amount

                }

            }

        });

    }

    // =====================================================

    // Transfer

    // =====================================================

    /**

     * Record an Account-to-Account Transfer.

     *

     * One economic event.

     *

     * Two Financial Lines because two accounts

     * are affected.

     */

    recordTransfer(data = {}) {

        const {

            date,

            fromAccountId,

            toAccountId,

            amount,

            currency = "USD",

            description = "",

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "TRANSFER",

            currency,

            description,

            source,

            lines: [

                {

                    accountId:

                        fromAccountId,

                    type: "TRANSFER",

                    amount,

                    direction: "OUT",

                    cashEffect: true,

                    category:

                        "Transfer",

                    description

                },

                {

                    accountId:

                        toAccountId,

                    type: "TRANSFER",

                    amount,

                    direction: "IN",

                    cashEffect: true,

                    category:

                        "Transfer",

                    description

                }

            ],

            businessDetails: {}

        });

    }

    // =====================================================

    // Investment Buy

    // =====================================================

    /**

     * Record an Investment Buy Actual event.

     *

     * IMPORTANT:

     *

     * Investment module calculates:

     *

     * - quantity

     * - price

     * - gross amount

     * - commission

     * - tax

     * - total cost

     * - cost basis

     *

     * TransactionService does NOT calculate them.

     *

     * It records the already calculated result.

     */

    recordInvestmentBuy(data = {}) {

        const {

            date,

            accountId,

            amount,

            currency = "USD",

            description = "",

            investment = {},

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "INVESTMENT_BUY",

            currency,

            description,

            source,

            lines: [

                {

                    accountId,

                    type: "EXPENSE",

                    amount,

                    direction: "OUT",

                    cashEffect: true,

                    category:

                        "Investment Purchase",

                    description

                }

            ],

            businessDetails: {

                investment: {

                    ...investment,

                    transactionAction:

                        "BUY",

                    transactionAmount:

                        amount

                }

            }

        });

    }

    // =====================================================

    // Investment Sell

    // =====================================================

    /**

     * Record an Investment Sell Actual event.

     *

     * IMPORTANT:

     *

     * Investment module calculates:

     *

     * - quantity

     * - sale price

     * - gross proceeds

     * - commission

     * - tax

     * - net proceeds

     * - cost basis

     * - capital gain / loss

     * - holding period

     * - short-term / long-term classification

     *

     * TransactionService only records the result.

     */

    recordInvestmentSell(data = {}) {

        const {

            date,

            accountId,

            amount,

            currency = "USD",

            description = "",

            investment = {},

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "INVESTMENT_SELL",

            currency,

            description,

            source,

            lines: [

                {

                    accountId,

                    type: "PROCEEDS",

                    amount,

                    direction: "IN",

                    cashEffect: true,

                    category:

                        "Investment Sale",

                    description

                }

            ],

            businessDetails: {

                investment: {

                    ...investment,

                    transactionAction:

                        "SELL",

                    transactionAmount:

                        amount

                }

            }

        });

    }

    // =====================================================

    // Dividend

    // =====================================================

    /**

     * Record a Dividend Actual event.

     */

    recordDividend(data = {}) {

        const {

            date,

            accountId,

            amount,

            currency = "USD",

            description = "",

            investment = {},

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "DIVIDEND",

            currency,

            description,

            source,

            lines: [

                {

                    accountId,

                    type: "INCOME",

                    amount,

                    direction: "IN",

                    cashEffect: true,

                    category:

                        "Dividend",

                    description

                }

            ],

            businessDetails: {

                investment: {

                    ...investment,

                    transactionAction:

                        "DIVIDEND",

                    transactionAmount:

                        amount

                }

            }

        });

    }

    // =====================================================

    // Interest

    // =====================================================

    /**

     * Record an Interest Actual event.

     */

    recordInterest(data = {}) {

        const {

            date,

            accountId,

            amount,

            currency = "USD",

            description = "",

            investment = {},

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "INTEREST",

            currency,

            description,

            source,

            lines: [

                {

                    accountId,

                    type: "INCOME",

                    amount,

                    direction: "IN",

                    cashEffect: true,

                    category:

                        "Interest",

                    description

                }

            ],

            businessDetails: {

                investment: {

                    ...investment,

                    transactionAction:

                        "INTEREST",

                    transactionAmount:

                        amount

                }

            }

        });

    }

    // =====================================================

    // Loan Payment

    // =====================================================

    /**

     * Record a Loan Payment Actual event.

     *

     * IMPORTANT:

     *

     * One real-world payment is ONE Transaction.

     *

     * Example:

     *

     * Total payment = 5,000

     *

     * Principal = 4,500

     * Interest  =   500

     *

     * The account cash movement is ONE Financial Line:

     *

     * OUT 5,000

     *

     * The business meaning is stored separately:

     *

     * businessDetails.liability

     *

     * {

     *     principal: 4500,

     *     interest: 500,

     *     paymentAmount: 5000

     * }

     *

     * TransactionService does NOT calculate

     * principal or interest.

     */

    recordLoanPayment(data = {}) {

        const {

            date,

            accountId,

            amount,

            currency = "USD",

            description = "",

            liability = {},

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "LOAN_PAYMENT",

            currency,

            description,

            source,

            lines: [

                {

                    accountId,

                    type: "EXPENSE",

                    amount,

                    direction: "OUT",

                    cashEffect: true,

                    category:

                        "Loan Payment",

                    description

                }

            ],

            businessDetails: {

                liability: {

                    ...liability,

                    paymentAmount:

                        amount

                }

            }

        });

    }

    // =====================================================

    // Tax Payment

    // =====================================================

    /**

     * Record a Tax Payment Actual event.

     *

     * Tax module calculates the tax amount.

     *

     * TransactionService only records the

     * actual payment.

     */

    recordTaxPayment(data = {}) {

        const {

            date,

            accountId,

            amount,

            currency = "USD",

            description = "",

            tax = {},

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "TAX_PAYMENT",

            currency,

            description,

            source,

            lines: [

                {

                    accountId,

                    type: "TAX",

                    amount,

                    direction: "OUT",

                    cashEffect: true,

                    category:

                        "Tax",

                    description

                }

            ],

            businessDetails: {

                tax: {

                    ...tax,

                    paymentAmount:

                        amount

                }

            }

        });

    }

    // =====================================================

    // Fee

    // =====================================================

    /**

     * Record an actual financial fee.

     *

     * Examples:

     *

     * - Bank fee

     * - Brokerage fee

     * - Management fee

     * - Service fee

     */

    recordFee(data = {}) {

        const {

            date,

            accountId,

            amount,

            currency = "USD",

            description = "",

            fee = {},

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "FEE",

            currency,

            description,

            source,

            lines: [

                {

                    accountId,

                    type: "FEE",

                    amount,

                    direction: "OUT",

                    cashEffect: true,

                    category:

                        fee.category ||

                        "Fee",

                    description

                }

            ],

            businessDetails: {

                expense: {

                    ...fee,

                    amount,

                    expenseType:

                        "FEE"

                }

            }

        });

    }

    // =====================================================

    // Generic Asset Purchase

    // =====================================================

    /**

     * Record an Asset Purchase Actual event.

     *

     * Asset module determines the asset details.

     */

    recordAssetPurchase(data = {}) {

        const {

            date,

            accountId,

            amount,

            currency = "USD",

            description = "",

            asset = {},

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "ASSET_PURCHASE",

            currency,

            description,

            source,

            lines: [

                {

                    accountId,

                    type: "EXPENSE",

                    amount,

                    direction: "OUT",

                    cashEffect: true,

                    category:

                        "Asset Purchase",

                    description

                }

            ],

            businessDetails: {

                asset: {

                    ...asset,

                    transactionAction:

                        "PURCHASE",

                    transactionAmount:

                        amount

                }

            }

        });

    }

    // =====================================================

    // Generic Asset Sale

    // =====================================================

    /**

     * Record an Asset Sale Actual event.

     */

    recordAssetSale(data = {}) {

        const {

            date,

            accountId,

            amount,

            currency = "USD",

            description = "",

            asset = {},

            source = "BusinessModule"

        } = data;

        return this.recordTransaction({

            date,

            type: "ASSET_SALE",

            currency,

            description,

            source,

            lines: [

                {

                    accountId,

                    type: "PROCEEDS",

                    amount,

                    direction: "IN",

                    cashEffect: true,

                    category:

                        "Asset Sale",

                    description

                }

            ],

            businessDetails: {

                asset: {

                    ...asset,

                    transactionAction:

                        "SALE",

                    transactionAmount:

                        amount

                }

            }

        });

    }

    // =====================================================

    // Generic Transaction Query

    // =====================================================

    /**

     * Get a Transaction by ID.

     */

    getTransaction(transactionId) {

        return this.transactionManager

            .getTransaction(

                transactionId

            );

    }

    /**

     * Get all Actual Transactions.

     */

    getAllTransactions() {

        return this.transactionManager

            .getAllTransactions();

    }

    /**

     * Get Posted Actual Transactions.

     */

    getPostedTransactions() {

        return this.transactionManager

            .getPostedTransactions();

    }

    /**

     * Get Transactions associated with

     * an Account.

     */

    getTransactionsByAccount(

        accountId

    ) {

        return this.transactionManager

            .getTransactionsByAccount(

                accountId

            );

    }

    /**

     * Get Transactions by type.

     */

    getTransactionsByType(type) {

        return this.transactionManager

            .getTransactionsByType(

                type

            );

    }

    /**

     * Get Transactions by date range.

     */

    getTransactionsByDateRange(

        startDate,

        endDate

    ) {

        return this.transactionManager

            .getTransactionsByDateRange(

                startDate,

                endDate

            );

    }

    // =====================================================

    // Transaction Status

    // =====================================================

    /**

     * Post a Pending Transaction.

     */

    postTransaction(transactionId) {

        return this.transactionManager

            .postTransaction(

                transactionId

            );

    }

    /**

     * Void an Actual Transaction.

     *

     * Historical data is retained.

     */

    voidTransaction(transactionId) {

        return this.transactionManager

            .voidTransaction(

                transactionId

            );

    }

    /**

     * Update an existing Transaction.

     */

    updateTransaction(

        transactionId,

        updates = {}

    ) {

        return this.transactionManager

            .updateTransaction(

                transactionId,

                updates

            );

    }

}

/*

 * CommonJS export.

 *

 * TransactionManager, TransactionService,

 * and Transaction are currently using

 * CommonJS in the Transaction layer.

 */

module.exports =

    TransactionService;
